spring:
  application:
    name: musicvibe-api
  
  datasource:
    url: jdbc:h2:mem:musicvibe
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 8080

# Spotify API Configuration (Optional - leave empty for demo mode)
# Get your credentials from https://developer.spotify.com/dashboard
spotify:
  client:
    id: ${SPOTIFY_CLIENT_ID:}
    secret: ${SPOTIFY_CLIENT_SECRET:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.musicvibe: DEBUG
