---
apiVersion: v1
kind: Namespace
metadata:
  name: musicvibe

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicvibe
  namespace: musicvibe
  labels:
    app: musicvibe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: musicvibe
  template:
    metadata:
      labels:
        app: musicvibe
    spec:
      containers:
      - name: musicvibe
        image: temitayocharles/musicvibe:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: musicvibe-service
  namespace: musicvibe
  labels:
    app: musicvibe
spec:
  type: LoadBalancer
  selector:
    app: musicvibe
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 4000
    nodePort: 30080
  sessionAffinity: ClientIP
